# Generated by Django 3.0.8 on 2020-07-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.IntegerField(choices=[(1, 'internt'), (2, 'eksternt')], verbose_name='arrangementtype')),
                ('tittel', models.CharField(max_length=50)),
                ('info', models.TextField(verbose_name='beskrivelse')),
                ('memo', models.TextField(blank=True, verbose_name='kommentar')),
                ('tidspunkt', models.DateTimeField()),
                ('varighet', models.CharField(blank=True, max_length=22)),
                ('lokale', models.CharField(max_length=10)),
                ('banner', models.ImageField(upload_to='bannere/')),
            ],
            options={
                'verbose_name_plural': 'arrangementer',
            },
        ),
        migrations.CreateModel(
            name='Medlem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.IntegerField(choices=[(1, 'SIT'), (2, 'Regi'), (3, 'FK'), (4, 'VK'), (5, 'SO'), (6, 'TSS'), (7, 'TKS'), (8, 'SPO'), (9, 'UKA'), (10, 'ISFiT'), (11, 'MG'), (12, 'ITK'), (13, 'ARK'), (14, 'FG'), (15, 'KSG'), (16, 'KU'), (17, 'KLST'), (18, 'LØK'), (19, 'DG'), (20, 'Profil'), (21, 'ekstern')], default=1, verbose_name='medlemstype')),
                ('fornavn', models.CharField(max_length=30)),
                ('mellomnavn', models.CharField(blank=True, max_length=30)),
                ('etternavn', models.CharField(max_length=30)),
                ('fodsel', models.DateField(verbose_name='fødselsdato')),
                ('opptak', models.IntegerField(verbose_name='opptaksår')),
                ('ugjeng', models.IntegerField(choices=[(1, 'Kostyme'), (2, 'Kulisse'), (3, 'Skuespill')], verbose_name='undergjeng')),
                ('status', models.IntegerField(choices=[(1, 'aktiv'), (2, 'veteran'), (3, 'pangsionist'), (4, 'permittert')])),
                ('portrett', models.ImageField(blank=True, default='katt.png', upload_to='medlemmer/')),
                ('telefon', models.CharField(max_length=8, verbose_name='telefonnummer')),
                ('epost', models.EmailField(max_length=60, verbose_name='e-postadresse')),
                ('studium', models.CharField(max_length=30)),
                ('jobb', models.CharField(blank=True, max_length=30)),
                ('kallenavn', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'medlemmer',
            },
        ),
        migrations.CreateModel(
            name='Produksjon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.IntegerField(choices=[(1, 'SIT'), (2, 'AFEI'), (3, 'UKA')], default=1, verbose_name='produksjonstype')),
                ('revy', models.BooleanField(default=False)),
                ('tittel', models.CharField(max_length=50)),
                ('info', models.TextField(verbose_name='beskrivelse')),
                ('memo', models.TextField(blank=True, verbose_name='kommentar')),
                ('forfatter', models.CharField(max_length=100)),
                ('opphav', models.IntegerField(verbose_name='opphavsår')),
                ('varighet', models.CharField(blank=True, max_length=12)),
                ('lokale', models.CharField(max_length=50)),
                ('banner', models.ImageField(blank=True, default='banner.png', upload_to='bannere/')),
                ('plakat', models.ImageField(blank=True, default='plakat.png', upload_to='plakater/')),
                ('program', models.FileField(blank=True, upload_to='programmer/')),
                ('film', models.FileField(blank=True, upload_to='filmer/')),
                ('blestestart', models.DateField(blank=True, null=True, verbose_name='blæstestart')),
                ('FBlink', models.CharField(blank=True, max_length=100, verbose_name='Facebook-link')),
                ('billettlink', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'produksjoner',
            },
        ),
        migrations.CreateModel(
            name='Verv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtype', models.IntegerField(choices=[(1, 'genfors'), (2, 'produksjon')], verbose_name='vervtype')),
                ('styre', models.BooleanField(default=False)),
                ('ansvar', models.BooleanField(default=True)),
                ('tittel', models.CharField(max_length=50)),
                ('info', models.TextField(blank=True, verbose_name='beskrivelse')),
                ('instruks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'verv',
            },
        ),
        migrations.CreateModel(
            name='Utmerkelse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utype', models.IntegerField(choices=[(1, 'ridder'), (2, 'kommandør'), (3, 'storkors')], verbose_name='utmerkelsestype')),
                ('dato', models.DateField()),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utmerkelser', to='SITdata.Medlem')),
            ],
            options={
                'verbose_name_plural': 'utmerkelser',
            },
        ),
        migrations.CreateModel(
            name='Sitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sitat', models.TextField(max_length=100)),
                ('dato', models.DateField()),
                ('kontekst', models.CharField(max_length=50)),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitater', to='SITdata.Medlem')),
            ],
            options={
                'verbose_name_plural': 'sitater',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftype', models.IntegerField(choices=[(1, 'scene'), (2, 'kostyme'), (3, 'kulisse'), (4, 'arrangement'), (5, 'sosialt')], verbose_name='fototype')),
                ('FG', models.BooleanField()),
                ('FGlink', models.CharField(blank=True, max_length=100, verbose_name='FG-link')),
                ('foto', models.ImageField(blank=True, upload_to='bilder/')),
                ('dato', models.DateField(blank=True)),
                ('kontekst', models.TextField()),
                ('arrangement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='SITdata.Arrangement')),
                ('produksjon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='SITdata.Produksjon')),
            ],
            options={
                'verbose_name_plural': 'fotoer',
            },
        ),
        migrations.CreateModel(
            name='Forestilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tidspunkt', models.DateTimeField()),
                ('produksjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forestillinger', to='SITdata.Produksjon')),
            ],
            options={
                'verbose_name_plural': 'forestillinger',
            },
        ),
        migrations.CreateModel(
            name='Erfaring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar', models.IntegerField(blank=True, verbose_name='år')),
                ('rolle', models.CharField(blank=True, max_length=30)),
                ('skriv', models.FileField(blank=True, upload_to='erfaringsskriv/', verbose_name='erfaringsskriv')),
                ('medlem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erfaringer', to='SITdata.Medlem')),
                ('produksjon', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='erfaringer', to='SITdata.Produksjon')),
                ('verv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erfaringer', to='SITdata.Verv')),
            ],
            options={
                'verbose_name_plural': 'erfaringer',
            },
        ),
        migrations.CreateModel(
            name='Anmeldelse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forfatter', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=50)),
                ('dato', models.DateField()),
                ('tekst', models.FileField(upload_to='anmeldelser/')),
                ('utdrag', models.TextField(blank=True)),
                ('produksjon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anmeldelser', to='SITdata.Produksjon')),
            ],
            options={
                'verbose_name_plural': 'anmeldelser',
            },
        ),
    ]
