# Generated by Django 3.0.8 on 2020-07-30 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erfaring',
            name='produksjon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='erfaringer', to='SITdata.Produksjon'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='SITdata.Arrangement'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='produksjon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='SITdata.Produksjon'),
        ),
    ]
