# Generated by Django 3.0.8 on 2020-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0002_auto_20200730_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='ftype',
            field=models.IntegerField(choices=[(1, 'scene'), (2, 'kostyme'), (3, 'kulisse'), (4, 'arbeid'), (5, 'arrangement'), (6, 'sosialt')], verbose_name='fototype'),
        ),
    ]
