# Generated by Django 3.1.5 on 2021-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0003_auto_20210125_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verv',
            name='vtype',
            field=models.IntegerField(choices=[(1, 'styre'), (2, 'gjeng'), (3, 'produksjons')], verbose_name='vervtype'),
        ),
    ]
