# Generated by Django 3.0.8 on 2020-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0004_auto_20200730_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='dato',
            field=models.DateField(blank=True, null=True),
        ),
    ]
