# Generated by Django 3.0.8 on 2021-01-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0004_auto_20210131_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['mtype', '-opptaksar', 'undergjeng', 'etternavn', 'fornavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AlterField(
            model_name='medlem',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='telefonnummer'),
        ),
    ]
