# Generated by Django 3.0.8 on 2020-07-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0005_auto_20200730_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='banner',
            field=models.ImageField(blank=True, upload_to='bannere/'),
        ),
    ]
