# Generated by Django 3.0.8 on 2021-02-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0006_auto_20210131_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='verv',
            name='epost',
            field=models.EmailField(blank=True, max_length=60, verbose_name='e-postadresse'),
        ),
        migrations.AddField(
            model_name='verv',
            name='henvendelser',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='verv',
            name='vtype',
            field=models.IntegerField(choices=[(1, 'styre'), (2, 'ekstern-gjeng'), (3, 'intern-gjeng'), (4, 'produksjons')], verbose_name='vervtype'),
        ),
    ]
