# Generated by Django 3.0.8 on 2020-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0006_auto_20200730_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erfaring',
            name='ar',
            field=models.IntegerField(blank=True, null=True, verbose_name='år'),
        ),
    ]
