# Generated by Django 3.0.8 on 2021-02-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0007_auto_20210201_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anmeldelse',
            name='forfatter',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anmeldelse',
            name='medium',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='FBlink',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook-link'),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='varighet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='dokument',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dtag',
            name='tag',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='navn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='rolle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='tittel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='foto',
            name='FGlink',
            field=models.CharField(blank=True, max_length=200, verbose_name='FG-link'),
        ),
        migrations.AlterField(
            model_name='hendelse',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lokale',
            name='navn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='epost',
            field=models.EmailField(blank=True, max_length=100, verbose_name='e-postadresse'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='etternavn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='fornavn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='jobb',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='kallenavn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='mellomnavn',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='studium',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='telefon',
            field=models.CharField(blank=True, max_length=100, verbose_name='telefonnummer'),
        ),
        migrations.AlterField(
            model_name='nummer',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='FBlink',
            field=models.CharField(blank=True, max_length=200, verbose_name='Facebook-link'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='billettlink',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='forfatter',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='varighet',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ptag',
            name='tag',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sitat',
            name='tekst',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uttrykk',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='verv',
            name='tittel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vtag',
            name='tag',
            field=models.CharField(max_length=60),
        ),
    ]
