# Generated by Django 3.0.8 on 2020-07-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0007_auto_20200730_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlem',
            name='portrett',
            field=models.ImageField(blank=True, default='portretter/katt.png', upload_to='portretter/'),
        ),
    ]
