# Generated by Django 3.0.8 on 2021-02-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0008_auto_20210205_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtag',
            options={'ordering': ['tag'], 'verbose_name': 'dokumenttag', 'verbose_name_plural': 'dokumenttags'},
        ),
        migrations.AlterModelOptions(
            name='ptag',
            options={'ordering': ['tag'], 'verbose_name': 'produksjonstag', 'verbose_name_plural': 'produksjonstags'},
        ),
        migrations.AlterModelOptions(
            name='vtag',
            options={'ordering': ['tag'], 'verbose_name': 'vervtag', 'verbose_name_plural': 'vervtags'},
        ),
    ]
