# Generated by Django 3.0.8 on 2020-07-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0008_auto_20200731_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlem',
            name='portrett',
            field=models.ImageField(default='portretter/katt.png', upload_to='portretter/'),
        ),
    ]
