# Generated by Django 3.0.8 on 2020-08-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0009_auto_20200731_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrangement',
            name='banner',
            field=models.ImageField(default='banner.png', upload_to='bannere/'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='banner',
            field=models.ImageField(default='banner.png', upload_to='bannere/'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='plakat',
            field=models.ImageField(default='plakat.png', upload_to='plakater/'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='varighet',
            field=models.CharField(blank=True, max_length=22),
        ),
    ]
