# Generated by Django 3.1.5 on 2021-02-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0010_auto_20210206_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erfaring',
            name='rolle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
