# Generated by Django 3.0.8 on 2021-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0010_auto_20210206_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlem',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'aktiv'), (2, 'veteran'), (3, 'pangsjonist'), (4, 'inaktiv')], null=True),
        ),
    ]
