# Generated by Django 3.0.8 on 2020-08-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0010_auto_20200801_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anmeldelse',
            options={'ordering': ['dato'], 'verbose_name_plural': 'anmeldelser'},
        ),
        migrations.AlterModelOptions(
            name='arrangement',
            options={'ordering': ['tidspunkt', 'tittel'], 'verbose_name_plural': 'arrangementer'},
        ),
        migrations.AlterModelOptions(
            name='forestilling',
            options={'ordering': ['tidspunkt'], 'verbose_name_plural': 'forestillinger'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['ftype'], 'verbose_name_plural': 'fotoer'},
        ),
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['etternavn', 'fornavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AlterModelOptions(
            name='produksjon',
            options={'ordering': ['ptype', 'tittel'], 'verbose_name_plural': 'produksjoner'},
        ),
        migrations.AlterModelOptions(
            name='sitat',
            options={'ordering': ['dato'], 'verbose_name_plural': 'sitater'},
        ),
        migrations.AlterModelOptions(
            name='utmerkelse',
            options={'ordering': ['dato'], 'verbose_name_plural': 'utmerkelser'},
        ),
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['vtype', 'tittel'], 'verbose_name_plural': 'verv'},
        ),
    ]
