# Generated by Django 3.0.8 on 2020-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0011_auto_20200801_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verv',
            name='ansvar',
        ),
        migrations.RemoveField(
            model_name='verv',
            name='styre',
        ),
        migrations.AlterField(
            model_name='verv',
            name='vtype',
            field=models.IntegerField(choices=[(1, 'styre'), (2, 'genfors'), (3, 'prod_merf'), (4, 'prod_uerf')], verbose_name='vervtype'),
        ),
    ]
