# Generated by Django 3.0.8 on 2021-02-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0012_auto_20210207_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumenttag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'dokumenttags',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Produksjonstag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'produksjonstags',
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Vervtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'vervtags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddField(
            model_name='dokument',
            name='dokumenttags',
            field=models.ManyToManyField(blank=True, to='SITdata.Dokumenttag'),
        ),
        migrations.AddField(
            model_name='produksjon',
            name='produksjonstags',
            field=models.ManyToManyField(blank=True, to='SITdata.Produksjonstag'),
        ),
        migrations.AddField(
            model_name='verv',
            name='vervtags',
            field=models.ManyToManyField(blank=True, to='SITdata.Vervtag'),
        ),
        migrations.AlterModelOptions(
            name='dokumenttag',
            options={'ordering': ['tag'], 'verbose_name_plural': 'dokumenttags'},
        ),
        migrations.AlterModelOptions(
            name='erfaring',
            options={'ordering': ['produksjon__premieredato', 'ar', 'verv__vervtype', 'verv__erfaringsoverforing', 'verv__tittel', 'tittel', 'medlem__etternavn', 'navn'], 'verbose_name_plural': 'erfaringer'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['fototype', 'produksjon__premieredato', 'arrangement__tidspunkt', 'dato'], 'verbose_name_plural': 'fotoer'},
        ),
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['medlemstype', '-opptaksar', 'undergjeng', 'etternavn', 'fornavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AlterModelOptions(
            name='produksjonstag',
            options={'ordering': ['tag'], 'verbose_name_plural': 'produksjonstags'},
        ),
        migrations.AlterModelOptions(
            name='verv',
            options={'ordering': ['vervtype', 'erfaringsoverforing', 'tittel'], 'verbose_name_plural': 'verv'},
        ),
        migrations.AlterModelOptions(
            name='vervtag',
            options={'ordering': ['tag'], 'verbose_name_plural': 'vervtags'},
        ),
        migrations.RenameField(
            model_name='anmeldelse',
            old_name='gratis',
            new_name='offentlig',
        ),
        migrations.RenameField(
            model_name='nummer',
            old_name='tekst',
            new_name='manus',
        ),
        migrations.RenameField(
            model_name='sitat',
            old_name='tekst',
            new_name='utsagn',
        ),
        migrations.RemoveField(
            model_name='arrangement',
            name='atype',
        ),
        migrations.AddField(
            model_name='arrangement',
            name='offentlig',
            field=models.BooleanField(default=False),
        ),
        migrations.RenameField(
            model_name='arrangement',
            old_name='blurb',
            new_name='reklame',
        ),
        migrations.RenameField(
            model_name='arrangement',
            old_name='info',
            new_name='beskrivelse',
        ),
        migrations.RenameField(
            model_name='arrangement',
            old_name='memo',
            new_name='anekdoter',
        ),
        migrations.RenameField(
            model_name='erfaring',
            old_name='skriv',
            new_name='erfaringsskriv',
        ),
        migrations.RenameField(
            model_name='foto',
            old_name='ftype',
            new_name='fototype',
        ),
        migrations.RenameField(
            model_name='medlem',
            old_name='mtype',
            new_name='medlemstype',
        ),
        migrations.RenameField(
            model_name='nummer',
            old_name='info',
            new_name='beskrivelse',
        ),
        migrations.RenameField(
            model_name='nummer',
            old_name='memo',
            new_name='anekdoter',
        ),
        migrations.RenameField(
            model_name='produksjon',
            old_name='blurb',
            new_name='reklame',
        ),
        migrations.RenameField(
            model_name='produksjon',
            old_name='info',
            new_name='beskrivelse',
        ),
        migrations.RenameField(
            model_name='produksjon',
            old_name='memo',
            new_name='anekdoter',
        ),
        migrations.RenameField(
            model_name='produksjon',
            old_name='ptype',
            new_name='produksjonstype',
        ),
        migrations.RenameField(
            model_name='verv',
            old_name='vtype',
            new_name='vervtype',
        ),
        migrations.AlterField(
            model_name='foto',
            name='fototype',
            field=models.IntegerField(choices=[(1, 'scene'), (2, 'kostyme'), (3, 'kulisse'), (4, 'arbeid'), (5, 'gruppe'), (6, 'dalje'), (7, 'arrangement'), (8, 'sosialt')]),
        ),
        migrations.AddField(
            model_name='foto',
            name='nummer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilder', to='SITdata.Nummer'),
        ),
        migrations.AddField(
            model_name='medlem',
            name='offentlig_portrett',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='anmeldelse',
            name='produksjon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anmeldelser', to='SITdata.Produksjon'),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='medlem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erfaringer', to='SITdata.Medlem'),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='produksjon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erfaringer', to='SITdata.Produksjon'),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='verv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='erfaringer', to='SITdata.Verv'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='arrangement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilder', to='SITdata.Arrangement'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='produksjon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bilder', to='SITdata.Produksjon'),
        ),
        migrations.AlterField(
            model_name='nummer',
            name='produksjon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='numre', to='SITdata.Produksjon'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='blestestart',
            field=models.DateField(blank=True, null=True, verbose_name='blæstestart'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='forfatter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='medlemspris',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='pris',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ar',
            fields=[
                ('arstall', models.IntegerField(primary_key=True, serialize=False, verbose_name='årstall')),
                ('styrebilde', models.ImageField(blank=True, upload_to='styrebilder/')),
                ('forsidetittel', models.CharField(blank=True, max_length=200)),
                ('forsidetekst', models.TextField(blank=True)),
                ('opptaksstart', models.DateField(blank=True, null=True)),
                ('soknadsfrist', models.DateTimeField(blank=True, null=True, verbose_name='søknadsfrist')),
                ('opptakstekst', models.TextField(blank=True)),
                ('varmotestart', models.DateField(blank=True, null=True, verbose_name='vårmøtestart')),
                ('varmotestopp', models.DateField(blank=True, null=True, verbose_name='vårmøtestopp')),
                ('hostmotestart', models.DateField(blank=True, null=True, verbose_name='høstmøtestart')),
                ('hostmotestopp', models.DateField(blank=True, null=True, verbose_name='høstmøtestopp')),
                ('genforstidspunkt', models.DateTimeField(blank=True, null=True)),
                ('forsidebilde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='SITdata.Foto')),
            ],
            options={
                'verbose_name': 'år',
                'verbose_name_plural': 'år',
                'ordering': ['arstall'],
            },
        ),
    ]
