# Generated by Django 3.0.8 on 2021-02-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0013_auto_20210215_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokument',
            name='dtags',
        ),
        migrations.RemoveField(
            model_name='produksjon',
            name='ptags',
        ),
        migrations.RemoveField(
            model_name='verv',
            name='vtags',
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='anekdoter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='reklame',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='erfaring',
            name='erfaringsskriv',
            field=models.FileField(blank=True, upload_to='erfaringsskriv/'),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='medlemstype',
            field=models.IntegerField(choices=[(1, 'SIT'), (2, 'Regi'), (3, 'FK'), (4, 'VK'), (5, 'SO'), (6, 'TSS'), (7, 'TKS'), (8, 'SPO'), (9, 'UKA'), (10, 'ISFiT'), (11, 'MG'), (12, 'ITK'), (13, 'ARK'), (14, 'FG'), (15, 'KSG'), (16, 'KU'), (17, 'KLST'), (18, 'LØK'), (19, 'DG'), (20, 'Profil'), (21, 'ekstern')], default=1),
        ),
        migrations.AlterField(
            model_name='nummer',
            name='anekdoter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nummer',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='anekdoter',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='beskrivelse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='produksjonstype',
            field=models.IntegerField(choices=[(1, 'SIT'), (2, 'KUP'), (3, 'AFEI'), (4, 'UKA')], default=1),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='reklame',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='verv',
            name='vervtype',
            field=models.IntegerField(choices=[(1, 'styre'), (2, 'ekstern-gjeng'), (3, 'intern-gjeng'), (4, 'produksjons')]),
        ),
        migrations.DeleteModel(
            name='dTag',
        ),
        migrations.DeleteModel(
            name='pTag',
        ),
        migrations.DeleteModel(
            name='vTag',
        ),
    ]
