# Generated by Django 3.0.8 on 2020-08-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0013_utmerkelse_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utmerkelse',
            name='orden',
            field=models.IntegerField(choices=[(1, 'Den Gyldne Kat'), (2, 'De Sorte Faars Ridderskab'), (3, 'Den Træge Patron'), (4, 'Polyhymnia'), (5, 'Vrangstrupen'), (6, 'Minerva Polyhymnia')], default=1),
        ),
    ]
