# Generated by Django 3.0.8 on 2020-08-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0014_auto_20200801_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksjon',
            name='semester',
            field=models.CharField(default='V2020', max_length=5),
            preserve_default=False,
        ),
    ]
