# Generated by Django 3.0.8 on 2021-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0015_auto_20210215_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erfaring',
            options={'ordering': ['-produksjon__premieredato', '-ar', 'verv__vervtype', 'verv__erfaringsoverforing', 'verv__tittel', 'tittel', 'medlem__etternavn', 'navn'], 'verbose_name_plural': 'erfaringer'},
        ),
    ]
