# Generated by Django 3.0.8 on 2020-08-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0015_produksjon_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produksjon',
            options={'ordering': ['ptype', 'semester', 'tittel'], 'verbose_name_plural': 'produksjoner'},
        ),
        migrations.AddField(
            model_name='produksjon',
            name='ar',
            field=models.IntegerField(default=2020, verbose_name='år'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='banner',
            field=models.ImageField(default='bannere/banner.png', upload_to='bannere/'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='plakat',
            field=models.ImageField(default='plakater/plakat.png', upload_to='plakater/'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='semester',
            field=models.IntegerField(choices=[(1, 'vår'), (2, 'høst')]),
        ),
    ]
