# Generated by Django 3.1.7 on 2021-02-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0015_auto_20210215_2016'),
        ('SITdata', '0011_auto_20210209_2003'),
    ]

    operations = [
    ]
