# Generated by Django 3.0.8 on 2021-03-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0016_auto_20210310_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anmeldelse',
            options={'ordering': ['forfatter', '-produksjon__premieredato'], 'verbose_name_plural': 'anmeldelser'},
        ),
        migrations.AlterModelOptions(
            name='ar',
            options={'ordering': ['-arstall'], 'verbose_name': 'år', 'verbose_name_plural': 'år'},
        ),
        migrations.AlterModelOptions(
            name='arrangement',
            options={'ordering': ['-tidspunkt', 'tittel'], 'verbose_name_plural': 'arrangementer'},
        ),
        migrations.AlterModelOptions(
            name='dokument',
            options={'ordering': ['-dato', 'tittel'], 'verbose_name_plural': 'dokumenter'},
        ),
        migrations.AlterModelOptions(
            name='foto',
            options={'ordering': ['-produksjon__premieredato', '-arrangement__tidspunkt', '-dato', 'fototype'], 'verbose_name_plural': 'fotoer'},
        ),
        migrations.AlterModelOptions(
            name='hendelse',
            options={'ordering': ['-dato', 'tittel'], 'verbose_name_plural': 'hendelser'},
        ),
        migrations.AlterModelOptions(
            name='nummer',
            options={'ordering': ['-produksjon__premieredato', 'tittel'], 'verbose_name_plural': 'numre'},
        ),
        migrations.AlterModelOptions(
            name='produksjon',
            options={'ordering': ['-premieredato', 'produksjonstype', 'tittel'], 'verbose_name_plural': 'produksjoner'},
        ),
        migrations.AlterModelOptions(
            name='utmerkelse',
            options={'ordering': ['orden', '-ar', 'tittel'], 'verbose_name_plural': 'utmerkelser'},
        ),
        migrations.RemoveField(
            model_name='ar',
            name='opptakstekst',
        ),
        migrations.RemoveField(
            model_name='nummer',
            name='opptak',
        ),
        migrations.RemoveField(
            model_name='produksjon',
            name='opptak',
        ),
        migrations.AddField(
            model_name='ar',
            name='opptaksbilde_annet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='annetopptaksar', to='SITdata.Foto', verbose_name='opptaksbilde (annet)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptaksbilde_kostyme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kostymeopptaksar', to='SITdata.Foto', verbose_name='opptaksbilde (kostyme)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptaksbilde_kulisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kulisseopptaksar', to='SITdata.Foto', verbose_name='opptaksbilde (kulisse)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptaksbilde_skuespill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skuespillopptaksar', to='SITdata.Foto', verbose_name='opptaksbilde (skuespill)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptakstekst_annet',
            field=models.TextField(blank=True, verbose_name='opptakstekst (annet)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptakstekst_kostyme',
            field=models.TextField(blank=True, verbose_name='opptakstekst (kostyme)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptakstekst_kulisse',
            field=models.TextField(blank=True, verbose_name='opptakstekst (kulisse)'),
        ),
        migrations.AddField(
            model_name='ar',
            name='opptakstekst_skuespill',
            field=models.TextField(blank=True, verbose_name='opptakstekst (skuespill)'),
        ),
        migrations.AlterField(
            model_name='ar',
            name='forsidebilde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forsider', to='SITdata.Foto'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='produksjonstype',
            field=models.IntegerField(choices=[(1, 'SIT'), (2, 'KUP'), (3, 'AFEI'), (4, 'UKA'), (5, 'ISFiT')], default=1),
        ),
        migrations.CreateModel(
            name='Opptak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opptakstype', models.IntegerField(choices=[(1, 'video'), (2, 'lyd')])),
                ('dato', models.DateField(blank=True, null=True)),
                ('fil', models.FileField(upload_to='opptak/')),
                ('kontekst', models.TextField()),
                ('arrangement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opptak', to='SITdata.Arrangement')),
                ('medlemmer', models.ManyToManyField(blank=True, to='SITdata.Medlem')),
                ('nummer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opptak', to='SITdata.Nummer')),
                ('produksjon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opptak', to='SITdata.Produksjon')),
            ],
            options={
                'verbose_name_plural': 'opptak',
                'ordering': ['-produksjon__premieredato', '-arrangement__tidspunkt', '-dato', 'opptakstype'],
            },
        ),
    ]
