# Generated by Django 3.0.8 on 2021-03-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0017_auto_20210313_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='offentlig',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='opptak',
            name='kilde',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utdrag', to='SITdata.Opptak'),
        ),
        migrations.AddField(
            model_name='opptak',
            name='kildestart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opptak',
            name='kildestopp',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opptak',
            name='offentlig',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='medlem',
            name='medlemstype',
            field=models.IntegerField(choices=[(1, 'SIT'), (2, 'Regi'), (3, 'FK'), (4, 'VK'), (5, 'SO'), (6, 'TSS'), (7, 'TKS'), (8, 'SPO'), (9, 'UKA'), (10, 'ISFiT'), (11, 'MG'), (12, 'ITK'), (13, 'ARK'), (14, 'FG'), (15, 'KSG'), (16, 'KU'), (17, 'KLST'), (18, 'LØK'), (19, 'DG'), (20, 'SM'), (21, 'Profil'), (22, 'ekstern')], default=1),
        ),
        migrations.AlterField(
            model_name='opptak',
            name='fil',
            field=models.FileField(blank=True, upload_to='opptak/'),
        ),
    ]
