# Generated by Django 3.0.8 on 2020-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0017_auto_20200808_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produksjon',
            name='premiere',
            field=models.DateTimeField(),
        ),
    ]
