# Generated by Django 3.0.8 on 2020-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0018_auto_20200808_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verv',
            name='vtype',
            field=models.IntegerField(choices=[(1, 'styreverv'), (2, 'ansvarsverv'), (3, 'produksjonsverv_med_erfaringsskriv'), (4, 'produksjonsverv_uten_erfaringsskriv')], verbose_name='vervtype'),
        ),
    ]
