# Generated by Django 3.2 on 2021-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0018_auto_20210324_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produksjon',
            name='medlemspris',
            field=models.IntegerField(blank=True, null=True, verbose_name='medlempris (kr)'),
        ),
        migrations.AlterField(
            model_name='produksjon',
            name='pris',
            field=models.IntegerField(blank=True, null=True, verbose_name='pris (kr)'),
        ),
    ]
