# Generated by Django 4.1.2 on 2023-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0019_auto_20210502_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='fototype',
            field=models.IntegerField(choices=[(1, 'scene'), (2, 'kostyme'), (3, 'kulisse'), (4, 'arbeids'), (5, 'dalje'), (6, 'arrangements'), (7, 'gruppe'), (8, 'sosialt')]),
        ),
    ]
