# Generated by Django 3.0.8 on 2020-08-11 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SITdata', '0019_auto_20200809_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erfaring',
            options={'ordering': ['ar', 'produksjon__premiere', 'verv__vtype', 'verv__tittel'], 'verbose_name_plural': 'erfaringer'},
        ),
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['opptak', 'etternavn', 'fornavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AddField(
            model_name='medlem',
            name='konto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
