# Generated by Django 3.1 on 2020-08-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0019_auto_20200809_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='erfaring',
            options={'ordering': ['ar', 'produksjon__premiere', 'verv__vtype', 'verv__tittel'], 'verbose_name_plural': 'erfaringer'},
        ),
    ]
