# Generated by Django 3.0.8 on 2020-08-11 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SITdata', '0020_auto_20200811_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medlem',
            name='konto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='brukerkonto'),
        ),
    ]
