# Generated by Django 4.1.2 on 2023-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0020_alter_foto_fototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='kontekst',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='opptak',
            name='kontekst',
            field=models.TextField(blank=True),
        ),
    ]
