# Generated by Django 3.0.8 on 2020-08-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0021_auto_20200811_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['opptak', 'ugjeng', 'etternavn', 'fornavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.AlterField(
            model_name='verv',
            name='vtype',
            field=models.IntegerField(choices=[(1, 'styre'), (2, 'genfors'), (3, 'prod_merf'), (4, 'prod_uerf')], verbose_name='vervtype'),
        ),
    ]
