# Generated by Django 3.0.8 on 2020-08-18 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SITdata', '0022_auto_20200812_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medlem',
            options={'ordering': ['opptak', 'undergjeng', 'etternavn', 'fornavn'], 'verbose_name_plural': 'medlemmer'},
        ),
        migrations.RemoveField(
            model_name='medlem',
            name='konto',
        ),
        migrations.RemoveField(
            model_name='medlem',
            name='ugjeng',
        ),
        migrations.AddField(
            model_name='medlem',
            name='brukerkonto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medlem',
            name='undergjeng',
            field=models.IntegerField(choices=[(1, 'Kostyme'), (2, 'Kulisse'), (3, 'Skuespill')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='verv',
            name='vtype',
            field=models.IntegerField(choices=[(1, 'styre'), (2, 'års'), (3, 'prod_merf'), (4, 'prod_uerf')], verbose_name='vervtype'),
        ),
    ]
