# Generated by Django 3.1 on 2020-09-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0020_auto_20200818_1707'),
        ('SITdata', '0023_auto_20200818_1838'),
    ]

    operations = [
    ]
