# Generated by Django 3.1 on 2020-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SITdata', '0024_merge_20200913_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='produksjon',
            name='ikke_medlemspris',
            field=models.IntegerField(blank=True, null=True, verbose_name='Billettpris ikke-medlem'),
        ),
        migrations.AddField(
            model_name='produksjon',
            name='medlemspris',
            field=models.IntegerField(blank=True, null=True, verbose_name='Billettpris medlem'),
        ),
    ]
